# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = ""
  weight = 10

[[main]]
  name = "Leaders"
  url = "leaders/"
  weight = 15

[[main]]
  name = "Stats by Team"
  url = "teams/"
  weight = 20

[[main]]
  parent = "Stats by Team"
  name = "Doosan Bears"
  url = "teams/doosanbears"
  weight = 101

[[main]]
  parent = "Stats by Team"
  name = "Hanwha Eagles"
  url = "teams/hanwhaeagles"
  weight = 102

[[main]]
  parent = "Stats by Team"
  name = "Kia Tigers"
  url = "teams/kiatigers"
  weight = 103

[[main]]
  parent = "Stats by Team"
  name = "Kiwoom Heroes"
  url = "teams/kiwoomheroes"
  weight = 104

[[main]]
  parent = "Stats by Team"
  name = "KT Wiz"
  url = "teams/ktwiz"
  weight = 105

[[main]]
  parent = "Stats by Team"
  name = "LG Twins"
  url = "teams/lgtwins"
  weight = 106

[[main]]
  parent = "Stats by Team"
  name = "Lotte Giants"
  url = "teams/lottegiants"
  weight = 107

[[main]]
  parent = "Stats by Team"
  name = "NC Dinos"
  url = "teams/ncdinos"
  weight = 108

[[main]]
  parent = "Stats by Team"
  name = "Samsung Lions"
  url = "teams/samsunglions"
  weight = 109

[[main]]
  parent = "Stats by Team"
  name = "SSG Landers"
  url = "teams/ssglanders"
  weight = 110

[[main]]
  name = "Elo Ratings"
  url = "elo/"
  weight = 30

[[main]]
  name = "FAQ"
  url = "faq/"
  weight = 40


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
