---
date: "2020-03-31"
title: 'KBO Leaders, 2024 Season'
---

**Batters** | [WAR](#warbat) | [wRC+](#wrcplus) | [OPS](#ops) | [ISO](#iso) | 
<br>
**Pitchers** | [WAR](#warpit) | [FIP](#fip) | [xFIP](#xfip) | [K/9](#k9) |
<br>
**Fielders** | [C](#c) | [1B](#first) | [2B](#second) | [2B](#second) | [3B](#third) | [SS](#ss) | [LF](#left) | [CF](#center) | [RF](#right) |


***
### WAR, Batters {#warbat}
```{r, echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(dplyr))
suppressMessages(library(kableExtra))
stats <- readRDS("~/GoogleDrive/KBO/kbo_stats.rds") %>% filter(season == max(season))
limit <- max(stats$batGp, na.rm = T) * 1.5

d <- stats %>% filter(batPa > limit) %>% select(playerId,playerNameKor,Name,TeamNameEng,age,pos,batWAR) %>% arrange(desc(batWAR))
d <- d[1:10,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,0,2), row.names = T, col.names = c("Name","Team","Age","Pos","WAR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T)  %>% column_spec(2, bold = T, border_right = F)
```
***
### wRC+ {#wrcplus}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(batPa > limit) %>% select(playerId,playerNameKor,Name,TeamNameEng,age,pos,wRCplus) %>% arrange(desc(wRCplus))
d <- d[1:10,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,0,1), row.names = T, col.names = c("Name","Team","Age","Pos","wRC+")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### OPS {#ops}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(batPa > limit) %>% select(playerId,playerNameKor,Name,TeamNameEng,age,pos,batOps) %>% arrange(desc(batOps))
d <- d[1:10,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,0,3), row.names = T, col.names = c("Name","Team","Age","Pos","OPS")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### ISO {#iso}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(batPa > limit) %>% select(playerId,playerNameKor,Name,TeamNameEng,age,pos,ISO) %>% arrange(desc(ISO))
d <- d[1:10,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,0,3), row.names = T, col.names = c("Name","Team","Age","Pos","ISO")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### WAR, Pitchers {#warpit}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pitIp2 > limit) %>% select(playerId,playerNameKor,Name,TeamNameEng,age,pitWAR) %>% arrange(desc(pitWAR))
d <- d[1:10,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,2), row.names = T, col.names = c("Name","Team","Age","WAR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### FIP {#fip}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pitIp2 > limit) %>% select(playerId,playerNameKor,Name,TeamNameEng,age,FIP) %>% arrange(FIP)
d <- d[1:10,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,2), row.names = T, col.names = c("Name","Team","Age","FIP")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### xFIP {#xfip}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pitIp2 > limit) %>% select(playerId,playerNameKor,Name,TeamNameEng,age,xFIP) %>% arrange(xFIP)
d <- d[1:10,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,2), row.names = T, col.names = c("Name","Team","Age","xFIP")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### K/9 {#k9}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pitIp2 > limit) %>% select(playerId,playerNameKor,Name,TeamNameEng,age,K9) %>% arrange(desc(K9))
d <- d[1:10,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,1), row.names = T, col.names = c("Name","Team","Age","K/9")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### SFR (C) {#c}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pos == "C") %>% select(playerId,playerNameKor,Name,TeamNameEng,age,SFR) %>% arrange(desc(SFR))
d <- d[1:3,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,1), row.names = T, col.names = c("Name","Team","Age","SFR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### SFR (1B) {#first}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pos == "1B") %>% select(playerId,playerNameKor,Name,TeamNameEng,age,SFR) %>% arrange(desc(SFR))
d <- d[1:3,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,1), row.names = T, col.names = c("Name","Team","Age","SFR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### SFR (2B) {#second}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pos == "2B") %>% select(playerId,playerNameKor,Name,TeamNameEng,age,SFR) %>% arrange(desc(SFR))
d <- d[1:3,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,1), row.names = T, col.names = c("Name","Team","Age","SFR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### SFR (3B) {#third}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pos == "3B") %>% select(playerId,playerNameKor,Name,TeamNameEng,age,SFR) %>% arrange(desc(SFR))
d <- d[1:3,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,1), row.names = T, col.names = c("Name","Team","Age","SFR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### SFR (SS) {#ss}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pos == "SS") %>% select(playerId,playerNameKor,Name,TeamNameEng,age,SFR) %>% arrange(desc(SFR))
d <- d[1:3,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,1), row.names = T, col.names = c("Name","Team","Age","SFR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### SFR (LF) {#left}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pos == "LF") %>% select(playerId,playerNameKor,Name,TeamNameEng,age,SFR) %>% arrange(desc(SFR))
d <- d[1:3,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,1), row.names = T, col.names = c("Name","Team","Age","SFR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### SFR (CF) {#center}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pos == "CF") %>% select(playerId,playerNameKor,Name,TeamNameEng,age,SFR) %>% arrange(desc(SFR))
d <- d[1:3,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,1), row.names = T, col.names = c("Name","Team","Age","SFR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
***
### SFR (RF) {#right}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- stats %>% filter(pos == "RF") %>% select(playerId,playerNameKor,Name,TeamNameEng,age,SFR) %>% arrange(desc(SFR))
d <- d[1:3,]
d$Name <- paste0("[", d$Name," | ",d$playerNameKor, "](/players/", d$playerId, ")")
d$TeamNameEng <- paste0("[", d$TeamNameEng, "](/teams/", gsub("[[:space:]]", "", tolower(d$TeamNameEng)), ")")
d <- d %>% select(-playerId,-playerNameKor)
kable(d, digits = c(0,0,0,1), row.names = T, col.names = c("Name","Team","Age","SFR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(2, bold = T, border_right = F)
```
