---
date: "2020-03-31"
title: 'KBO Leaders, 2015 Season'
---
**Overall** | [WAR](#war) | **Batters** | [WAR](#warbat) | [wRC+](#wrcplus) | [OPS](#ops) | [ISO](#iso) | **Pitchers** | [WAR](#warpit) | [FIP](#fip) | [K/9](#k9) |
<br>
**Season** | [2021](/leaders/) | [2020](/leaders-2020) | [2019](/leaders-2019) | [2018](/leaders-2018/) | [2017](/leaders-2017) | [2016](/leaders-2016) | [2015](/leaders-2015) | [2014](/leaders-2014) |

***
### WAR, Overall {#war}
```{r, echo=F,warning=FALSE,message=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
batters <- read_csv("~/Google Drive/KBO/batters_simple.csv")
pitchers <- read_csv("~/Google Drive/KBO/pitchers_simple.csv")
batters <- unique(batters) 
pitchers <- unique(pitchers)
batters <- batters %>% filter(Year == 2015) %>% subset(PA > 446)
pitchers <- pitchers %>% filter(Year == 2015) %>% subset(as.numeric(IP2) > 100)
batwar <- batters %>% select(Code,Name,Team,Position,WAR)
pitwar <- pitchers %>% select(Code,Name,Team,Position,WAR)
d <- rbind(batwar,pitwar)
d <- d %>% arrange(desc(WAR))
d <- d[1:10,]
names(d)[2] <- "Name"
d$Name <- paste0("[", d$Name, "](/players/", d$Code, ")")
d$Team <- paste0("[", d$Team, "](/teams/", gsub("[[:space:]]", "", d$Team), ")")
d$Rank <- 1:10
d <- d %>% select(Rank, Name, Team, Position, WAR)
kable(d, digits = c(0,0,0,0,2), col.names = c("Rank","Name","Team","Pos","WAR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T)  %>% column_spec(2, bold = T, border_right = F)
```
***
### WAR, Batters {#warbat}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- batters %>% select(Code,Name,Team,Position,WAR) %>% arrange(desc(WAR))
d <- d[1:10,]
names(d)[2] <- "Name"
d$Name <- paste0("[", d$Name, "](/players/", d$Code, ")")
d$Team <- paste0("[", d$Team, "](/teams/", gsub("[[:space:]]", "", d$Team), ")")
d$Rank <- 1:10
d <- d %>% select(Rank, Name, Team, Position, WAR)
kable(d, digits = c(0,0,0,0,2), col.names = c("Rank","Name","Team","Pos","WAR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T)  %>% column_spec(2, bold = T, border_right = F)
```
***
### wRC+ {#wrcplus}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- batters %>% select(Code,Name,Team,Position,wRCplus) %>% arrange(desc(wRCplus))
d <- d[1:10,]
names(d)[2] <- "Name"
d$Name <- paste0("[", d$Name, "](/players/", d$Code, ")")
d$Team <- paste0("[", d$Team, "](/teams/", gsub("[[:space:]]", "", d$Team), ")")
d$Rank <- 1:10
d <- d %>% select(Rank, Name, Team, Position, wRCplus)
kable(d, digits = c(0,0,0,0,1), col.names = c("Rank","Name","Team","Pos","wRC+")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T)  %>% column_spec(2, bold = T, border_right = F)
```
***
### OPS {#ops}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- batters %>% select(Code,Name,Team,Position,OPS) %>% arrange(desc(OPS))
d <- d[1:10,]
names(d)[2] <- "Name"
d$Name <- paste0("[", d$Name, "](/players/", d$Code, ")")
d$Team <- paste0("[", d$Team, "](/teams/", gsub("[[:space:]]", "", d$Team), ")")
d$Rank <- 1:10
d <- d %>% select(Rank, Name, Team, Position, OPS)
kable(d, digits = c(0,0,0,0,3), col.names = c("Rank","Name","Team","Pos","OPS")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T)  %>% column_spec(2, bold = T, border_right = F)
```
***
### ISO {#iso}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- batters %>% select(Code,Name,Team,Position,ISO) %>% arrange(desc(ISO))
d <- d[1:10,]
names(d)[2] <- "Name"
d$Name <- paste0("[", d$Name, "](/players/", d$Code, ")")
d$Team <- paste0("[", d$Team, "](/teams/", gsub("[[:space:]]", "", d$Team), ")")
d$Rank <- 1:10
d <- d %>% select(Rank, Name, Team, Position, ISO)
kable(d, digits = c(0,0,0,0,3), col.names = c("Rank","Name","Team","Pos","ISO")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T)  %>% column_spec(2, bold = T, border_right = F)
```
***
### WAR, Pitchers {#warpit}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- pitchers %>% select(Code,Name,Team,Position,WAR) %>% arrange(desc(WAR))
d <- d[1:10,]
names(d)[2] <- "Name"
d$Name <- paste0("[", d$Name, "](/players/", d$Code, ")")
d$Team <- paste0("[", d$Team, "](/teams/", gsub("[[:space:]]", "", d$Team), ")")
d$Rank <- 1:10
d <- d %>% select(Rank, Name, Team, Position, WAR)
kable(d, digits = c(0,0,0,0,2), col.names = c("Rank","Name","Team","Pos","WAR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T)  %>% column_spec(2, bold = T, border_right = F)
```
***
### FIP {#fip}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- pitchers %>% select(Code,Name,Team,Position,FIP) %>% arrange(FIP)
d <- d[1:10,]
names(d)[2] <- "Name"
d$Name <- paste0("[", d$Name, "](/players/", d$Code, ")")
d$Team <- paste0("[", d$Team, "](/teams/", gsub("[[:space:]]", "", d$Team), ")")
d$Rank <- 1:10
d <- d %>% select(Rank, Name, Team, Position, FIP)
kable(d, digits = c(0,0,0,0,2), col.names = c("Rank","Name","Team","Pos","FIP")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T)  %>% column_spec(2, bold = T, border_right = F)
```
***
### K/9 {#k9}
```{r, echo=F,warning=FALSE,message=FALSE}
d <- pitchers %>% select(Code,Name,Team,Position,SO9) %>% arrange(desc(SO9))
d <- d[1:10,]
names(d)[2] <- "Name"
d$Name <- paste0("[", d$Name, "](/players/", d$Code, ")")
d$Team <- paste0("[", d$Team, "](/teams/", gsub("[[:space:]]", "", d$Team), ")")
d$Rank <- 1:10
d <- d %>% select(Rank, Name, Team, Position, SO9)
kable(d, digits = c(0,0,0,0,2), col.names = c("Rank","Name","Team","Pos","K/9")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T)  %>% column_spec(2, bold = T, border_right = F)
```