---
date: "2024-07-31"
title: 'Privacy Policy'
---

KBO Fancy Stats is a project of [Niche Analytics](https://nicheanalytics.org/). We do not collect any personal data from you, however Google uses cookies to help serve the ads it displays on the websites of its partners, such as websites displaying Google ads or participating in Google certified ad networks. When users visit a Google partner's website, a cookie may be dropped on that end user's browser.

- Third party vendors, including Google, use cookies to serve ads based on a user's prior visits to your website or other websites.
- Google's use of advertising cookies enables it and its partners to serve ads to your users based on their visit to your sites and/or other sites on the Internet.
- Users may opt out of personalized advertising by visiting Ads Settings: https://www.google.com/settings/ads

What are your data protection rights?

Every user is entitled to the following:

The right to access – You have the right to request copies of your personal data. 

The right to rectification – You have the right to request correction any information you believe is inaccurate. You also have the right to request completion the information you believe is incomplete.

The right to erasure – You have the right to request removal of your personal data, under certain conditions.

The right to restrict processing – You have the right to request restriction of the processing of your personal data, under certain conditions.

The right to object to processing – You have the right to object to the processing of your personal data, under certain conditions.

The right to data portability – You have the right to request the transfer of any collected data to another organization, or directly to you, under certain conditions.


Cookies
Cookies are text files placed on your computer to collect standard Internet log information and visitor behavior information. When you visit our websites, we may collect information from you automatically through cookies or similar technology

For further information, visit allaboutcookies.org.


Privacy policies of other websites
This site may contain links to other websites. Our privacy policy applies only to our website, so if you click on a link to another website, you should read their privacy policy.

Changes to our privacy policy
Our Company keeps its privacy policy under regular review and places any updates on this web page. This privacy policy was last updated on 21 July 2024.

How to contact us
If you have any questions about Our Company’s privacy policy, the data we hold on you, or you would like to exercise one of your data protection rights, please do not hesitate to contact us.

Email us at: info@nicheanalytics.org
