---
date: "2021-03-31"
summary: 'WAR Leader | Yang Eui-ji, C: 5.26'
title: 'NC Dinos'
subtitle: 'Changwon | Current Elo: 1507 (5)'
image:
  preview_only: true
---
**2021** | [Batting](#batting) | [Pitching](#pitching) | 
**2020** | [Batting](https://www.kbofancystats.com/teams-2020/NCDinos/#batting) | [Pitching](https://www.kbofancystats.com/teams-2020/NCDinos/#pitching) | 
 
***
### 2021 Batting Stats {#batting}
```{r pressure, echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(dplyr))
suppressMessages(library(readr))
suppressMessages(library(kableExtra))
batters <- suppressMessages(read_csv("~/Google Drive/KBO/batters_simple.csv", col_types = cols(.default = "?", Year = "c", Age = "c")))
batters <- batters[complete.cases(batters),]
batters$Age <- as.numeric(batters$Age)
d <- batters %>% filter(Team == "NC Dinos") %>% filter(Year == "2021") %>% select(-Team, -Year, -KName, -Url)
d <- d[order(-d$WAR),]
d$Name <- paste0("[", d$Name, "](/players/", d$Code, ")")
d <- d %>% select(-Code)
kable(d, digits = c(0,0,0,0,0,0,3,1,1,3,3,1,2), col.names = c("Name","Age","Pos","G","PA","HR","OPS","BB%","SO%","ISO","BABIP","wRC+","WAR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>%column_spec(1, bold = T, border_right = F)
```
***
### 2021 Pitching Stats {#pitching}
```{r, echo=F,warning=FALSE,message=FALSE}
pitchers <- suppressMessages(read_csv("~/Google Drive/KBO/pitchers_simple.csv", col_types = cols(.default = "?", Year = "c", Age = "c")))
pitchers <- pitchers[complete.cases(pitchers),]
d <- pitchers %>% filter(Team == "NC Dinos") %>% filter(Year == "2021") %>% select(-Team, -Year, -KName, -Position, -Url)
d <- d[order(-d$WAR),]
d$Name <- paste0("[", d$Name, "](/players/", d$Code, ")")
d <- d %>% select(-Code)
kable(d, digits = c(0,0,0,0,1,1,1,1,3,3,2,2), col.names = c("Name","Age","G","GS","IP","K/9","BB/9","HR/9","BABIP","ERA","FIP","WAR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(1, bold = T, border_right = F)
```
