---
date: "2020-03-02"
title: "What do these fancy stats mean?"
summary: "WAR? wRC+? FIP?"
---

Here are brief descriptions of the stats used on this site. For more about the origin of these measures, how they are calculated, and the cutting edge of baseball analytics, we recommend [FanGraphs' library](https://library.fangraphs.com/).

**Stats** | [BABIP](#babip) | [BB% & SO%](#bbso) | [BB/9, K/9 & HR/9](#bbkhr) | [xGB%](#xgbpct) | [ISO](#iso) | [FIP & xFIP](#fip) | [SFR](#sfr) | [wOBA](#woba) | [wRC+](#wrc) | [WAR](#war) |

***
 
### BABIP {#babip}
*Batting Average on Balls In Play.* The concept of BABIP is simple, it is just batting average but with home runs and strikeouts removed from the equation. But why should we care? As it turns out, hitters don't have much control over whether a batted ball falls in for a hit or not, and pitchers have even less control. Instead, it is mostly a product of defense or luck, though hitting the ball hard does help. This means that BABIP tends to regress toward the league average of .300, especially for pitchers. A higher BABIP early in a season probably means that a hitter has been a bit lucky or a pitcher has been a bit unlucky. BABIP is especially useful for assessing whether hot or cold streaks are for real or likely to evaporate.

### BB% & SO% {#bbso}
Our batting stats include walk rate and strikeout rate, to give an idea of a hitters general skill set. Check out the quartiles below for helpful context. 

### BB/9, K/9 & HR/9 {#bbkhr}
For pitchers, we include rate stats for each of the "three true outcomes," the name given to walks, strikeouts, and home runs, because they are the three things a pitcher can control himself—the defense plays a role in everything else.

### xGB% {#xgbpct}
*Expected Groundball %.* Home runs are one of the three true outcomes for pitchers. But what if they aren't, exactly? Pitchers may have more control over how often they allow flyballs, than how many of those flys leave the yard. Groundball percentage is interesting on its own and also necessary to calculate [xFIP](#fip). Unfortunately, KBO play-by-play data only gives us access to ground*out* percentage, so we use [Carson Cistulli's](https://blogs.fangraphs.com/converting-goao-to-gb/) formula for xGB% instead. 

### ISO {#iso}
*Isolated Power.* ISO is simply slugging percentage minus batting average. It is a quick way to identify a slugger. For example, a high strikeout rate might not look so bad if paired with an elite ISO.

### FIP & xFIP {#fip}
*(Expected) Fielding Independent Pitching.* FIP attempts to recalculate ERA with the influence of defense removed. It is based on the three true outcomes (see above) and scaled to look just like ERA. In fact, FIP is usually a better predictor of future ERA than ERA itself. Even better than FIP is xFIP, which observes that pitchers have more control over fly balls than home runs and is calculated using *expected* home runs, based on flyball rate.

### SFR {#sfr}
*Simple Fielding Runs.* Even with the best of data, fielding metrics are tricky business. And we do not have the best of data. Thankfully, using play-by-play data we can calculate an approximation of [Dan Fox's](https://www.baseballprospectus.com/news/article/7072/schrodingers-bat-simple-fielding-runs-version-1-0/) Simple Fielding Runs, a measure of how many runs each fielder prevented compared to the average fielder, based on how often balls hit in their direction result in outs.

### wOBA {#woba}
*Weighted On Base Average.* wOBA is just like on base percentage, except that each event is weighted based on how many runs the average such event generates. Doubles, for example, tend to be worth about 1.25 runs, by the end of the inning. So, wOBA is the average number of runs a batter creates per plate appearance.

### wRC+ {#wrc}
*Weighted Runs Created Plus*. wRC+ is based on the same concept as wOBA, but it is adjusted so that the average wRC+ is 100 and each point above or below that is equal to a 1% difference. That means that in 2020, Kim Hyeon-su (wRC+: 138.6) created 38.6% more runs than the average hitter, holding plate appearances equal.

### WAR {#war}
*Wins Above Replacement*. WAR is simpler in concept than in calculation. A player's WAR is the number of games his team won thanks to him. For example, if the Doosan Bears didn't have Kim Jae-ho (WAR: 3.01) in 2019—and instead had a freely available, replacement-level player—they would have won three fewer games. How do we know that? For hitters, we base WAR on the same concept as wOBA and wRC+. We determine how many runs that player is responsible for and compare it to the number of runs a team needs, on average, to win. That number is then scaled to replacement level. Baseball Reference and FanGraphs have agreed that a team of replacement-level players should win about 30% of their games, and we set replacement level using their method. Ideally, a batter's WAR should also include his defensive and baserunning contributions, but modern WAR uses radar and video analysis data which is not publically available for the KBO. Our WAR, then, is based primarily on contributions at the plate, with an adjustment for stolen bases, caught stealings, and [SFR](#sfr). For pitchers, WAR is more straightforward. It is essentially FIP rescaled so that it is equivalent to hitters' WAR. For all players, WAR is cumulative, so when comparing two players, one of whom was injured for a long period or arrived mid-season, other stats are probably more useful.