---
date: "2021-03-31"
title: 'LG Twins'
subtitle: 'Seoul'
summary: 'WAR Leader: Hong Chang-ki (7.58)'
image:
  preview_only: true
---
[Batting](#batting) | [Pitching](#pitching)
 
***
### 2021 Batting Stats {#batting}
```{r batters, echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(kableExtra))
d <- readRDS("~/GoogleDrive/KBO/kbo_stats.rds")
d <- d[d$season == '2021' & d$TeamNameEng == 'LG Twins',]
vars <- c("Name","position","age","batPa","batBBpct","batSOpct","ISO","batBABIP","wOBA","wRCplus","batWAR")
players <- na.omit(d[c(vars,"playerId","playerNameKor")])
players$Name <- paste0("[", players$Name," | ",players$playerNameKor, "](/players/", players$playerId, ")")
players <- players[vars]
players <- players[order(-players[,11]),]
kable(players, digits = c(0,0,0,0,1,1,3,3,3,1,2), row.names = F, col.names = c("Name","Pos","Age","PA","BB%","SO%","ISO","BABIP","wOBA","wRC+","WAR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(1, bold = T, border_right = F)
```
***
### 2021 Pitching Stats {#pitching}
```{r pitchers, echo=F,warning=FALSE,message=FALSE}
vars <- c("Name","age","pitIp","K9","BB9","HR9","pitBABIP","xGBpct","xFIP","FIP","pitWAR")
players <- na.omit(d[c(vars,"playerId")])
players <- na.omit(d[c(vars,"playerId","playerNameKor")])
players$Name <- paste0("[", players$Name," | ",players$playerNameKor, "](/players/", players$playerId, ")")
players <- players[vars]
players <- players[order(-players[,11]),]
kable(players, digits = c(0,0,1,1,1,1,3,1,2,2,2), row.names = F, col.names = c("Name","Age","IP","K/9","BB/9","HR/9","BABIP","xGB%","xFIP","FIP","WAR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(1, bold = T, border_right = F)
```
