---
date: "2022-01-23"
title: 'Kia Tigers'
subtitle: 'Gwangju'
summary: 'WAR Leader: Na Sung-bum (6.99)'
image:
  preview_only: true
---
[Batting](#batting) | [Pitching](#pitching)
 
***
### 2022 Batting Stats {#batting}
```{r batters, echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(kableExtra))
d <- readRDS("~/GoogleDrive/KBO/kbo_stats.rds")
d <- d[d$season == '2022' & d$TeamNameEng == 'Kia Tigers',]
vars <- c("Name","pos","age","batPa","batBBpct","batSOpct","ISO","batBABIP","wRCplus","SFR","batWAR")
d$SFR <- ifelse(is.na(d$SFR),"N/A",round(d$SFR,1))
d$pos <- ifelse(is.na(d$pos),"DH",d$pos)
players <- na.omit(d[c(vars,"playerId","playerNameKor")])
players$Name <- paste0("[", players$Name," | ",players$playerNameKor, "](/players/", players$playerId, ")")
players <- players[vars]
players <- players[order(-players[,11]),]
kable(players, digits = c(0,0,0,0,1,1,3,3,1,1,2), row.names = F, col.names = c("Name","Pos","Age","PA","BB%","SO%","ISO","BABIP","wRC+","SFR","WAR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(1, bold = T, border_right = F)
```
***
### 2022 Pitching Stats {#pitching}
```{r pitchers, echo=F,warning=FALSE,message=FALSE}
vars <- c("Name","age","pitIp","K9","BB9","HR9","pitBABIP","xGBpct","xFIP","FIP","pitWAR")
players <- na.omit(d[c(vars,"playerId")])
players <- na.omit(d[c(vars,"playerId","playerNameKor")])
players$Name <- paste0("[", players$Name," | ",players$playerNameKor, "](/players/", players$playerId, ")")
players <- players[vars]
players <- players[order(-players[,11]),]
kable(players, digits = c(0,0,1,1,1,1,3,1,2,2,2), row.names = F, col.names = c("Name","Age","IP","K/9","BB/9","HR/9","BABIP","xGB%","xFIP","FIP","WAR")) %>% kable_styling(bootstrap_options = c("striped", "hover"), fixed_thead = T) %>% column_spec(1, bold = T, border_right = F)
```
